version: '3'

volumes:
  db-data-postgres:
    driver: local

  db-data-postgres-config:
    driver: local

services:
  hole-postgres:
    image: postgres:15beta2-bullseye
    container_name: hole-postgres
    environment:
      POSTGRES_DB: "hole_data"
      POSTGRES_USER: "hole_data"
      POSTGRES_PASSWORD: "hole_data"
      PGDATA: /var/lib/postgresql/data/pgdata
    restart: always
    ports:
      - "5432:5432"
    expose:
      - 5432
    networks:
      - hole-net
    volumes:
      - db-data-postgres:/var/lib/postgresql/data
      - db-data-postgres-config:/var/lib/postgresql/dataConfig

  hole:
    image: hole:0.3.0-beta.0
    container_name: hole
    networks:
      - hole-net
    ports:
      - "9191:9191"
    depends_on:
      - hole-postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://hole-postgres:5432/hole_data
      SPRING_PROFILES_ACTIVE: dev
    restart: on-failure
    volumes:
      - ~/.hole:/hole

networks:
  hole-net:
    driver: bridge
