spring:
  application:
    name: "hole"

  profiles:
    active: "production"

  main:
    banner-mode: off
    allow-circular-references: true

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/hole_data
    username: hole_data
    password: hole_data

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    hibernate:
      ddl-auto: none # required for liquibase migrations

  liquibase:
    change-log: db/changelog/db.changelog-main.xml

  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1

server:
  port: "9191"
  undertow:
    max-http-post-size: -1